_BASE_: "../Base-bagtricks.yml"

MODEL:
    #WEIGHTS: "./logs/product10k/softmax/model_final.pth"
    WEIGHTS: "./logs/product10k/softmax_npair_scale10/model_final.pth"
    # WEIGHTS: "./logs/product10k/circleSoft-Npair/model_final.pth"
    FREEZE_LAYERS: ["backbone"]
    META_ARCHITECTURE: "Baseline"
    BACKBONE:
        NAME: "build_resnet_backbone"
        NORM: "BN"
        DEPTH: "50x"
        WITH_NL: False
        LAST_STRIDE: 1
        WITH_IBN: False
        PRETRAIN: False
        PRETRAIN_PATH: "./model/ImageNet/resnet50-19c8e357.pth"
    HEADS:
        NAME: "ReductionHead"
        NECK_FEAT: "after"
        POOL_LAYER: "gempool"
        CLS_LAYER: ""
        SCALE: 64
        MARGIN: 0.35
        SCALE: 1
        MARGIN: 0.0
        REDUCTION_DIM: 512
    LOSSES:
        # NAME: ("CrossEntropyLoss", "TripletLoss",)
        # NAME: ("CrossEntropyLoss", "NpairLoss",)
        # NAME: ("CrossEntropyLoss", )
        NAME: ("NpairLoss", )
        CE:
            EPSILON: 0.1
            SCALE: 1.0
        TRI:
            MARGIN: 0.0
            HARD_MINING: True
            NORM_FEAT: False
            SCALE: 1.0
        NPAIR:
            MARGIN: 0.01
            SCALE: 5
            HARD_MINING: False

DATASETS:
    NAMES: ("Product10k",)
    SPLIT_FILE: "train_val_split.txt"
    TESTS: ("Product10k",)

INPUT:
    SIZE_TRAIN: [224, 224]
    SIZE_TEST: [224, 224]
    DO_AUTOAUG: True

DATALOADER:
    NUM_INSTANCE: 2

SOLVER:
    OPT: "Adam"
    MAX_ITER: 60
    BASE_LR: 0.00035
    BIAS_LR_FACTOR: 1.
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BIAS: 0.0005
    IMS_PER_BATCH: 64

    SCHED: "WarmupCosineAnnealingLR"
    DELAY_ITERS: 30
    ETA_MIN_LR: 0.00000077

    WARMUP_FACTOR: 0.01
    WARMUP_ITERS: 10
    FREEZE_ITERS: 10
    CHECKPOINT_PERIOD: 2

TEST:
    EVAL_INIT: True
    EVAL_PERIOD: 2
    IMS_PER_BATCH: 128
    ROC_ENABLED: True

CUDNN_BENCHMARK: True
OUTPUT_DIR: "./logs/product10k/softmax_npair_scale5"
