_BASE_: "../Base-bagtricks.yml"

MODEL:
    WEIGHTS: "./model/DukeMTMC/duke_bot_R50.pth"
    BACKBONE:
        PRETRAIN: False
        PRETRAIN_PATH: ""
        # NORM: "syncBN"
    HEADS:
        NAME: "ReductionHead"
        REDUCTION_DIM: 256
        # NORM: "syncBN"

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/bagtricks_R50_ReduceHead_CD"
