_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  WEIGHTS: "./model/DukeMTMC/duke_sbs_R50.pth"
  BACKBONE:
      PRETRAIN: False
      PRETRAIN_PATH: ""
      CD: True
      # NORM: "syncBN"
  HEADS:
      NAME: "ReductionHead"
      REDUCTION_DIM: 256
      # NORM: "syncBN"

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/sbs_R50_ReduceHead_CD8"
