_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
    WEIGHTS: "./model/R101-ibn/model_0034399_v1.5.pth"
    BACKBONE:
        DEPTH: "101x"
        WITH_IBN: True
        WITH_NL: True
        WITH_SE: False
        PRETRAIN: False
        PRETRAIN_PATH: ""
        NORM: "syncBN"
    HEADS:
        NORM: "syncBN"
        NECK_FEAT: "after"
        POOL_LAYER: "gempool"
        CLS_LAYER: "linear"
        SCALE: 64
        MARGIN: 0.35
        EXTRA_FEAT: 6

    LOSSES:
        NAME: ("CrossEntropyLoss", "TripletLoss",)
        CE:
            EPSILON: 0.1
            SCALE: 1.0
        TRI:
            MARGIN: 0.0
            HARD_MINING: True
            NORM_FEAT: False
            SCALE: 1.0
    # PIXEL_STD:
    # - 58.395
    # - -57.120000000000005
    # - -57.375

DATASETS:
    NAMES: ("NAIC", "REID2019")
    TESTS: ("NAIC",)
    # SPLIT_FILE: "REID2020_2019_train_val.txt"
    SPLIT_FILE: ""
  
DATALOADER:
    NUM_INSTANCE: 4
  
INPUT:
    CJ:
        ENABLED: False
        PROB: 0.2
        BRIGHTNESS: 0.15
        CONTRAST: 0.15
        SATURATION: 0.1
        HUE: 0.1
    RPT:
        ENABLED: False
        PROB: 0.2
    DO_PAD: False
    DO_AUTOAUG: False
    DO_AUGMIX: False
    REA:
        ENABLED: False
        PROB: 0.5
    RC:
        ENABLED: False
        PROB: 0.5
    SIZE_TRAIN: [256, 128]
    SIZE_TEST: [256, 128]

SOLVER:
    OPT: "Adam"
    MAX_ITER: 60
    BASE_LR: 0.00035
    BIAS_LR_FACTOR: 1.
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BIAS: 0.0005
    IMS_PER_BATCH: 128
  
    SCHED: "WarmupCosineAnnealingLR"
    DELAY_ITERS: 30
    ETA_MIN_LR: 0.00000077
  
    WARMUP_FACTOR: 0.01
    WARMUP_ITERS: 10
    FREEZE_ITERS: 10
    CHECKPOINT_PERIOD: 2
TEST:
    ENABLED: False 
    EVAL_INIT: False
    EVAL_PERIOD: 2
    IMS_PER_BATCH: 128
    ENABLED: True
    RERANK:
        ENABLED: False
        K1: 20
        K2: 6
        LAMBDA: 0.3
    # JSON_FILE: "sbs_R101-ibn_all_reverse_std_result.json"
  
OUTPUT_DIR: "logs/NAIC/sbs_R101-ibn-add-mean_std_feat"
