_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
    # FREEZE_LAYERS: [""]
    WEIGHTS: "./model/NAIC/msmt_sbs_R50.pth"
    BACKBONE:
        PRETRAIN: False
        PRETRAIN_PATH: ""
        CD: True
        NORM: "syncBN"

    HEADS:
        NORM: "syncBN"

DATASETS:
    NAMES: ("NAIC",)
    TESTS: ("NAIC",)

DATALOADER:
    NUM_INSTANCE: 4

INPUT:
    SIZE_TRAIN: [512, 256]
    SIZE_TEST: [512, 256]

# SOLVER:
#     IMS_PER_BATCH: 512
#     MAX_ITER: 20
#     BASE_LR: 0.0001

TEST:
    ENABLED: True
    EVAL_INIT: False
    EVAL_PERIOD: 2
    RERANK:
        ENABLED: False
    JSON_FILE: ''
    # IMS_PER_BATCH: 512

OUTPUT_DIR: "logs/naic/sbs_R50_cd"
