_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  # FREEZE_LAYERS: [""]
  WEIGHTS: "./logs/naic/sbs_R101_ibn/model_final.pth"
  BACKBONE:
    PRETRAIN: False
    PRETRAIN_PATH: ""
    CD: False
    DEPTH: "101x"
    WITH_IBN: True

DATASETS:
  NAMES: ("NAIC",)
  TESTS: ("NAIC",)

DATALOADER:
  NUM_INSTANCE: 4

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]

# SOLVER:
#   MAX_ITER: 20
#   BASE_LR: 0.0001

TEST:
  ENABLED: True
  EVAL_INIT: False
  RERANK:
    ENABLED: True
  JSON_FILE: 'logs/naic/ensemble/sbs-R50_sbs-R101.json'

OUTPUT_DIR: "logs/naic/ensemble"
