_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
    NAMES: ("NAIC",)
    TESTS: ("NAIC",)
    ROOT: ""
    SPLIT_FILE: "NAIC_train_val.txt"

OUTPUT_DIR: "logs/naic/sbs_R50-ibn"